//
// This file has been modified by Christof Krüger <jniBox2d@christof-krueger.de>.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class box2d_ContactImpulse */

#ifndef _Included_box2d_ContactImpulse
#define _Included_box2d_ContactImpulse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     box2d_ContactImpulse
 * Method:    jniGetNormalImpulses
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_box2d_ContactImpulse_jniGetNormalImpulses
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     box2d_ContactImpulse
 * Method:    jniGetTangentImpulses
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_box2d_ContactImpulse_jniGetTangentImpulses
  (JNIEnv *, jobject, jlong, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
