//
// This file has been modified by Christof Krüger <jniBox2d@christof-krueger.de>.
//

/**
* Copyright 2010 Mario Zechner (contact@badlogicgames.com)
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*   http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class box2d_joints_GearJoint */

#ifndef _Included_box2d_joints_GearJoint
#define _Included_box2d_joints_GearJoint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     box2d_joints_GearJoint
 * Method:    jniSetRatio
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_box2d_joints_GearJoint_jniSetRatio
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     box2d_joints_GearJoint
 * Method:    jniGetRatio
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_box2d_joints_GearJoint_jniGetRatio
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
