//
// This file has been modified by Christof Krüger <jniBox2d@christof-krueger.de>.
//

/**
* Copyright 2010 Mario Zechner (contact@badlogicgames.com)
* 
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
* 
*   http://www.apache.org/licenses/LICENSE-2.0
* 
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class box2d_Joint */

#ifndef _Included_box2d_Joint
#define _Included_box2d_Joint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     box2d_Joint
 * Method:    jniGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_box2d_Joint_jniGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_Joint
 * Method:    jniGetBodyA
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_box2d_Joint_jniGetBodyA
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_Joint
 * Method:    jniGetBodyB
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_box2d_Joint_jniGetBodyB
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_Joint
 * Method:    jniGetAnchorA
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_box2d_Joint_jniGetAnchorA
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     box2d_Joint
 * Method:    jniGetAnchorB
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_box2d_Joint_jniGetAnchorB
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     box2d_Joint
 * Method:    jniGetReactionForce
 * Signature: (JF[F)V
 */
JNIEXPORT void JNICALL Java_box2d_Joint_jniGetReactionForce
  (JNIEnv *, jobject, jlong, jfloat, jfloatArray);

/*
 * Class:     box2d_Joint
 * Method:    jniGetReactionTorque
 * Signature: (JF)F
 */
JNIEXPORT jfloat JNICALL Java_box2d_Joint_jniGetReactionTorque
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     box2d_Joint
 * Method:    jniIsActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_box2d_Joint_jniIsActive
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
