//
// This file has been modified by Christof Krüger <jniBox2d@christof-krueger.de>.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class box2d_PolygonShape */

#ifndef _Included_box2d_PolygonShape
#define _Included_box2d_PolygonShape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     box2d_PolygonShape
 * Method:    newPolygonShape
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_box2d_PolygonShape_newPolygonShape
  (JNIEnv *, jobject);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniSet
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_box2d_PolygonShape_jniSet
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniSetAsBox
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_box2d_PolygonShape_jniSetAsBox__JFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniSetAsBox
 * Signature: (JFFFFF)V
 */
JNIEXPORT void JNICALL Java_box2d_PolygonShape_jniSetAsBox__JFFFFF
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniSetAsEdge
 * Signature: (JFFFF)V
 */
JNIEXPORT void JNICALL Java_box2d_PolygonShape_jniSetAsEdge
  (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniGetVertexCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_box2d_PolygonShape_jniGetVertexCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_PolygonShape
 * Method:    jniGetVertex
 * Signature: (JI[F)V
 */
JNIEXPORT void JNICALL Java_box2d_PolygonShape_jniGetVertex
  (JNIEnv *, jobject, jlong, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
