//
// This file has been modified by Christof Krüger <jniBox2d@christof-krueger.de>.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class box2d_Shape */

#ifndef _Included_box2d_Shape
#define _Included_box2d_Shape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     box2d_Shape
 * Method:    jniGetRadius
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_box2d_Shape_jniGetRadius
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_Shape
 * Method:    jniSetRadius
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_box2d_Shape_jniSetRadius
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     box2d_Shape
 * Method:    jniDispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_box2d_Shape_jniDispose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     box2d_Shape
 * Method:    jniGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_box2d_Shape_jniGetType
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class box2d_Shape_Type */

#ifndef _Included_box2d_Shape_Type
#define _Included_box2d_Shape_Type
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
